name: Get Lottie Revision Hash

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-revision-hash:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (optional, if you need context from your repo)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Clone the lottie-spm repository
      - name: Clone lottie-spm
        run: |
          git clone --depth 1 --branch main https://github.com/airbnb/lottie-spm.git
        working-directory: ${{ runner.temp }}

      # Step 3: Get the latest commit hash
      - name: Get Revision Hash
        id: get_hash
        run: |
          cd ${{ runner.temp }}/lottie-spm
          REVISION_HASH=$(git rev-parse HEAD)
          echo "Revision Hash: $REVISION_HASH"
          echo "revision_hash=$REVISION_HASH" >> $GITHUB_OUTPUT
        working-directory: ${{ runner.temp }}

      # Step 4: Output the hash (optional, for visibility)
      - name: Display Revision Hash
        run: |
          echo "The revision hash for lottie-spm (main) is ${{ steps.get_hash.outputs.revision_hash }}"