name: Regenerate Xcode Project

on:
  push:
    branches:
      - main
    paths:
      - 'Package.swift'
  workflow_dispatch:  # Allows manual triggering

jobs:
  regenerate:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Run regenerate script
        run: |
          chmod +x ./regenerate-project.sh
          ./regenerate-project.sh
          
      - name: Save regenerated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: regenerated-project-files
          path: |
            backdoor.xcodeproj
            backdoor.xcworkspace
            Package.resolved
            
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backdoor.xcodeproj backdoor.xcworkspace Package.resolved
          git diff --quiet && git diff --staged --quiet || git commit -m "Regenerate Xcode project files from Package.swift"
          git push
