name: Regenerate Project Files

on:
  push:
    branches:
      - main
    paths:
      - 'Package.swift'
      - 'Project.swift'
  workflow_dispatch:  # Allows manual triggering

jobs:
  regenerate:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
          
      - name: Generate project files
        run: |
          tuist version
          tuist generate --no-open
          
      - name: Save regenerated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: regenerated-project-files
          path: |
            *.xcodeproj
            *.xcworkspace
            package.resolved
            
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.xcodeproj *.xcworkspace package.resolved
          git diff --quiet && git diff --staged --quiet || git commit -m "Regenerate project files from Package.swift"
          git push