name: Update Project Dependencies

on:
  # Run when the dep-bdg.json file is changed
  push:
    paths:
      - 'dep-bdg.json'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update of dependencies regardless of changes'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  update-dependencies:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install uuid

      - name: Update dependencies
        run: |
          python scripts/add_dependency.py --debug

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-dependencies
          commit-message: "Update dependencies"
          title: "Update dependencies"
          body: "This pull request updates the dependencies and includes any changes generated by the update script."
          labels: dependencies
          delete-branch: true